### ISSUE TITLE
Error when trying to create a new PCC file for ME2 on the latest Nightly release

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#187]
**Describe the bug**
When attempting to create a new package file for any of the games in the trilogy, I get an unhanded exception error, and am unable to create a new file.

**To Reproduce**
1. Go to 'Package Editor'
2. Click on 'File'
3. Choose any game, then click 'ok'
4. Choose a name, then save the file
5. See Error

**Expected behavior**
When you attempt to create a new package file in Package Editor, it will show an unhanded exception error, and not create the new package file.

**Version information:**
v4.2.0.1333 7/19/2020

![image](https://user-images.githubusercontent.com/54004034/87887173-fbf13380-c9df-11ea-98bd-5c36546ee5ac.png)

**Stack trace**
FileNotFoundException: Could not find file 'C:\Users\Emilio\Desktop\fdas.pcc'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at ME3Explorer.Packages.MEPackage.<>c.<RegisterLoader>b__41_0(String f, MEGame g)
   at ME3Explorer.Packages.MEPackageHandler.CreateAndSavePackage(String path, MEGame game)
   at ME3Explorer.PackageEditorWPF.NewFile()
   at ME3Explorer.SharedUI.GenericCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SirCxyrtyx** [comment]
Thanks for reporting this!
