### ISSUE TITLE
Cloning with all references keeps throwing relink errors and is failing to relink and/or bring over referenced exports/imports

### ISSUE THREAD

**Issue by mkhaar** [ME3Tweaks/LegendaryExplorer#292]
# Please fill out the following form *in its entirety*. 
The more information you provide, the easier it will be for us to reproduce the issue.

**Describe the bug**
Cloning with all references one thing from one file to another within the same game (haven't tried from across games) in LE2 is throwing the following error every time (to note, it's not even a BioPawn what's being cloned...):

```
Exception: Unable to add TheWorld.PersistentLevel.BioPawn to file! Could not find it!
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.EntryImporter.GetOrAddCrossImportOrPackage(String importFullNameInstanced, IMEPackage sourcePcc, IMEPackage destinationPCC, Boolean importNonPackageExportsToo, IDictionary`2 objectMapping, Nullable`1 forcedLink) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\EntryImporter.cs:line 503
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.relinkUIndex(IMEPackage importingPCC, ExportEntry relinkingExport, Int32& uIndex, String propertyName, IDictionary`2 crossPCCObjectMappingList, String prefix, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 409
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.relinkPropertiesRecursive(IMEPackage importingPCC, ExportEntry relinkingExport, PropertyCollection transplantProps, IDictionary`2 crossPCCObjectMappingList, String prefix, List`1 relinkResults, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 263
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.Relink(ExportEntry sourceExport, ExportEntry relinkingExport, IDictionary`2 crossPCCObjectMappingList, List`1 relinkReport, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 155
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.RelinkAll(IDictionary`2 crossPccObjectMap, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 57
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.EntryImporter.ImportAndRelinkEntries(PortingOption portingOption, IEntry sourceEntry, IMEPackage destPcc, IEntry targetLinkEntry, Boolean shouldRelink, IEntry& newEntry, Dictionary`2 relinkMap, Action`1 errorOccuredCallback, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\EntryImporter.cs:line 122
   at LegendaryExplorer.Tools.PackageEditor.PackageEditorWindow.GongSolutions.Wpf.DragDrop.IDropTarget.Drop(IDropInfo dropInfo) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\PackageEditor\PackageEditorWindow.xaml.cs:line 3343
   at GongSolutions.Wpf.DragDrop.DragDrop.DropTargetOnDrop(Object sender, DragEventArgs e, EventType eventType)
   at GongSolutions.Wpf.DragDrop.DragDrop.DropTargetOnDrop(Object sender, DragEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.OleDropTarget.RaiseDragEvent(RoutedEvent dragEvent, Int32 dragDropKeyStates, Int32& effects, DependencyObject target, Point targetPoint)
   at System.Windows.OleDropTarget.MS.Win32.UnsafeNativeMethods.IOleDropTarget.OleDrop(Object data, Int32 dragDropKeyStates, Int64 point, Int32& effects)
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DoDragSourceMove(Object sender, Point position)
   at GongSolutions.Wpf.DragDrop.DragDrop.DragSourceOnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**To Reproduce**

Open BioD_OmgHub_100Dock.pcc on Package Editor, from the DLC_METR_Patch01, not basegame. Go to export 3486, the one we want to clone "SFXSkeletalMeshActorMAT_13". Now, open BioD_PrsCvA_103CellBlock03 and try to clone with all references to its own persistent level (export 1019). LEX will throw a warning about needing to reindex the cloned export (as both files have conflicting exports with the same index) say yes/continue. Error gets triggered mentioning BioPawn, despite trying to clone a SFXSkeletalMeshActorMAT. Seemingly, the export gets cloned over BUT lots of references keep the export numbers of the original PCC, which, by the way, gets edited, with the original cloned export becoming yellow and changing index (which it shouldn't do) on the origin file.

This, by the way, was a big deal of an issue on the latest branch of ME3Explorer that apparently was fixed, but seems to have returned once again to LEX. As far as I can tell, anything I am attempting to clone from one file to another is triggering this behavior, with both original file being modified, and file being edited, having lots of bad references or them entirely missing. But since specific cases are requested, above is one I have been able to reproduce with the latest 2 nightlies and "stable".

**Expected behavior**
Cloning with all references should just work after reindexing the export, bringing over whatever references were needed either as imports/exports and not keep the numbers of the original file.

**Version information:**
6.0 NIGHTLY 10/21/2021 v6.0.0.3868

**Stack trace**

```
Exception: Unable to add TheWorld.PersistentLevel.BioPawn to file! Could not find it!
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.EntryImporter.GetOrAddCrossImportOrPackage(String importFullNameInstanced, IMEPackage sourcePcc, IMEPackage destinationPCC, Boolean importNonPackageExportsToo, IDictionary`2 objectMapping, Nullable`1 forcedLink) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\EntryImporter.cs:line 503
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.relinkUIndex(IMEPackage importingPCC, ExportEntry relinkingExport, Int32& uIndex, String propertyName, IDictionary`2 crossPCCObjectMappingList, String prefix, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 409
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.relinkPropertiesRecursive(IMEPackage importingPCC, ExportEntry relinkingExport, PropertyCollection transplantProps, IDictionary`2 crossPCCObjectMappingList, String prefix, List`1 relinkResults, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 263
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.Relink(ExportEntry sourceExport, ExportEntry relinkingExport, IDictionary`2 crossPCCObjectMappingList, List`1 relinkReport, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 155
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.Relinker.RelinkAll(IDictionary`2 crossPccObjectMap, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\Relinker.cs:line 57
   at LegendaryExplorerCore.Packages.CloningImportingAndRelinking.EntryImporter.ImportAndRelinkEntries(PortingOption portingOption, IEntry sourceEntry, IMEPackage destPcc, IEntry targetLinkEntry, Boolean shouldRelink, IEntry& newEntry, Dictionary`2 relinkMap, Action`1 errorOccuredCallback, Boolean importExportDependencies) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Packages\CloningImportingAndRelinking\EntryImporter.cs:line 122
   at LegendaryExplorer.Tools.PackageEditor.PackageEditorWindow.GongSolutions.Wpf.DragDrop.IDropTarget.Drop(IDropInfo dropInfo) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\PackageEditor\PackageEditorWindow.xaml.cs:line 3343
   at GongSolutions.Wpf.DragDrop.DragDrop.DropTargetOnDrop(Object sender, DragEventArgs e, EventType eventType)
   at GongSolutions.Wpf.DragDrop.DragDrop.DropTargetOnDrop(Object sender, DragEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.OleDropTarget.RaiseDragEvent(RoutedEvent dragEvent, Int32 dragDropKeyStates, Int32& effects, DependencyObject target, Point targetPoint)
   at System.Windows.OleDropTarget.MS.Win32.UnsafeNativeMethods.IOleDropTarget.OleDrop(Object data, Int32 dragDropKeyStates, Int64 point, Int32& effects)
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DoDragSourceMove(Object sender, Point position)
   at GongSolutions.Wpf.DragDrop.DragDrop.DragSourceOnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[github clone issue.zip](https://github.com/ME3Tweaks/LegendaryExplorer/files/7389003/github.clone.issue.zip)

**Comment by SirCxyrtyx** [comment]
Thanks for the bug report! This is fixed in the latest nightly.
