### ISSUE TITLE
Minor bugs: Custom classes adding properties

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#34]
**(1) When using custom classes adding a property to the default__ or other instances using the "Add property" dialog - fails.**

The dialog opens and you can select a new property to add but click "Add property" and an exception is created.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ME3Explorer.Interpreter.AddProperty(String prop) in C:\Users\Dev\Source\Repos\ME3Explorer\ME3Explorer\Interpreter\Interpreter.cs:line 2643
   at ME3Explorer.Interpreter.addPropButton_Click(Object sender, EventArgs e) in C:\Users\Dev\Source\Repos\ME3Explorer\ME3Explorer\Interpreter\Interpreter.cs:line 2635
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

(sample file uploaded to #pathfinders)

**(2) When using custom classes - adding certain array properties and structs shows parsing has failed.  Changing the class to a similar but in-database version allows the interpreter to function**

For example Add StartingPowerRanks struct to Default__SFXPawn_Volus

**Comment by Mgamerz** [comment]
Verify this for 3.0.10.4, thanks.

**Comment by Kinkojiro** [comment]
Yes, (1) is now fixed thanks.
(2) I am still getting problems with structs on occasion.
EG: StartingPowerRanks, WeaponAnimSpecs - if I change the class name to a native name eg. SFXPawn_Volus to SFXPawn_Grunt interpreter works again.
