### ISSUE TITLE
Bugs: Various small bugs in 3.1.2

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#38]
I am on a different PC than usual, but there appears to be a number of minor bugs with things that were working before:

(1) Adding a combat zone to a coverslot via right click in PathEd throws an exception (see below).
(2) PathEd, SeqEd and PackageEd all experience cases where they don't refresh properly.  Save and reload shows the action (for example a new link in SeqEd) was done, but it doesn't update prior to that.
(3) I had an issue with ME3Exp thinking several files that I was working on were corrupt.  I managed to open them later.  This maybe my PC rather than ME3Exp though.
(4) Add property to a targetpoint throws an exception (below)

Obvs until you get VB problems sorted, not much you can do, but wanted to post before I forget.

Notes:
Exception for add combatzone:
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ME3Explorer.PathfindingEditor.addCombatZoneRef(IExportEntry nodeExp, IExportEntry combatZoneExp) in C:\Users\Mgamerz\Source\Repos\ME3Explorer\ME3Explorer\Pathfinding Editor\PathfindingEditor.cs:line 1267
   at ME3Explorer.PathfindingEditor.<>c__DisplayClass65_1.<node_MouseDown>b__0(Object o, EventArgs args) in C:\Users\Mgamerz\Source\Repos\ME3Explorer\ME3Explorer\Pathfinding Editor\PathfindingEditor.cs:line 1185
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Exception for add property to targetpoint:
************* Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ME3Explorer.SharedUI.AddPropertyDialogWPF.GetProperty(IExportEntry export, List`1 _extantProps, MEGame game) in C:\Users\Mgamerz\Source\Repos\ME3Explorer\ME3Explorer\SharedUI\AddPropertyDialogWPF.xaml.cs:line 59
   at ME3Explorer.Interpreter.addPropButton_Click(Object sender, EventArgs e) in C:\Users\Mgamerz\Source\Repos\ME3Explorer\ME3Explorer\Interpreter\Interpreter.cs:line 2655
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Mgamerz** [comment]
I am working on combat zone stuff right now. That add to combat zone menu item actually never worked. I was working on it but right before I was able to finish it I took a break for my hands. I will look at 4) but 2) and 3) will be difficult without SirCyxrtyx (15th spelling time's a charm!)

**Comment by Mgamerz** [comment]
As far as I am aware all these bugs should be fixed now.
