### ISSUE TITLE
v3.1.14 WPF64: Various Issues and WIP ToDo functionality

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#54]
A list of items that either are not working, yet to be implemented etc.

**PackageEdWPF**
_Tree_

_Binary_
- Binary for Persistent Level cannot remove from list only add/replace

**_BUGS_**

_Interpreter Tab_

- Unfortunately many structs do not work (and don't work in PackEdOld either):
**_TO DO STRUCTS LIST:_**
- m_aBioPreLoadData (InterpData)

**Comment by Mgamerz** [comment]
I am merging WwiseBankEditor into the soundpanel subcontrol.  Once it is merged the original wwiseviewer will be axed.

**Comment by Mgamerz** [comment]
This list can be updated:

Clone functionality has been implemented

Offset to property start will not be fixed, rather the property uses new highlighting effect in hexbox
Remove Property has been implemented but needs better implementation to ensure it is properly removed (equality check may cause some issues when data is modified vs cached)

stringrefproperties have been implemented into interpreterwpf

BinaryInterpreter has been done except generic scan and editing abilities

Import/Export entry data has been implemented
Search/goto features have been properly implemented

Soundbank ID endians are not flipped. This is the actual value shown. I will make it so you can display it in big endian which is how humans read it.

**Comment by Kinkojiro** [comment]
Updated.

**Comment by Kinkojiro** [comment]
Updated.  Tested on  [https://github.com/Mgamerz/ME3Explorer/commit/a817d6b2eb3bce3b9e446250455675aedcf73a2a](a817d6b )

Drag and drop causes a crash in PackEdWPF  - whether or not using root directory
```ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at ME3Explorer.Packages.ExportEntry.GetPropertyStart()
   at ME3Explorer.Packages.ExportEntry.WriteProperties(PropertyCollection props)
   at ME3Explorer.PackageEditorWPF.relinkObjects2(IMEPackage importpcc)
   at ME3Explorer.PackageEditorWPF.GongSolutions.Wpf.DragDrop.IDropTarget.Drop(IDropInfo dropInfo)
   at GongSolutions.Wpf.DragDrop.DragDrop.DropTargetOnDrop(Object sender, DragEventArgs e) in D:\projects\git\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop.Shared\DragDrop.cs:line 626
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.OleDropTarget.RaiseDragEvent(RoutedEvent dragEvent, Int32 dragDropKeyStates, Int32& effects, DependencyObject target, Point targetPoint)
   at System.Windows.OleDropTarget.MS.Win32.UnsafeNativeMethods.IOleDropTarget.OleDrop(Object data, Int32 dragDropKeyStates, Int64 point, Int32& effects)
   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DragSourceOnMouseMove(Object sender, MouseEventArgs e) in D:\projects\git\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop.Shared\DragDrop.cs:line 462
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Mgamerz** [comment]
A hook for collection changed will need to be placed on the package namelist, import list, and export list as this list will be modified. This hook notification will refresh the list UI.

**Comment by Mgamerz** [comment]
This list needs to be updated with what needs to be done in _InterpreterWPF_. Adding and removing array properties, setting data types, adding and removing top level properties all need to be checked for all the different data types. I know I have not implemented them all (Like BioMask).

**Comment by Mgamerz** [comment]
Removing array properties implemented.

Needs to be able to add items, e.g. I tested and cannot add stringproperty to empty list yet.

**Comment by Mgamerz** [comment]
List can be updated:
 - InterpViewer link in Package Editor WPF, done
 - Binary for Persistent Level - can now add. Can't remove yet
 - Binary for BioDynamicAnimSet Set Button - now works with names

Bugs:
 - Need to validate property highlighting. It's significantly more complicated than I originally thought it would be as we cannot directly write the data to get the length (writing to get length at the wrong time can actually corrupt the file). I've been working on this, it's improving but not there yet
 - Adding struct properties works now for ME1/ME2/ME3 to arrays containing them, as long as the array has one item. I will be adding support for ME3 to add to add to an empty list, but I have to figure out how to generate the StructProperty to insert
 - ~~Metadata editor needs some checks for when exports, imports are added, and when package names are changed. The lists are cached and are not being refreshed. This should not be difficult, but identifying the place to refresh may take a bit~~ Needs validated

As for bug 1 in this list, this is due to a check not being done in the addName() method. Technically this is not a bug, but it can add a null name to the list, which can totally hose the file when saving. I am going to introduce an exception that will be thrown when this condition occurs, to prevent this from happening, as it is not obvious to the user when this occurs. Notably I have seen this when enum properties for ME1 and ME2 are attempted to be parsed that don't have a name attached because the type lookup failed.

**Comment by Kinkojiro** [comment]
Removed a large number of items from the list.

**Comment by Kinkojiro** [comment]
Given that structs are the issue mentioned in #73 I think you can close this.

**Comment by Mgamerz** [comment]
Structs should be able to be added to empty and populated arrays now, not just for ME3, but now for all 3 games in InterpreterWPF.

I will prepare a build. This will need tested.

**Comment by Mgamerz** [comment]
Additionally, `Binary for Persistent Level cannot remove from list only add/replace` will be moved to the next release. Once we can validate and test the remaining items in this issue, we can close this thread.
